title: REFED Dataset
description: "REFED: A Subject Real-time Dynamic Labeled EEG-fNIRS Synchronized Recorded Emotion Dataset"
theme: jekyll-theme-cayman
paper_link: https://neurips.cc/virtual/2025/poster/121785