title: "REFED: A Subject Real-time Dynamic Labeled EEG-fNIRS\n Synchronized Recorded Emotion Dataset"
description: "REFED: A Subject Real-time Dynamic Labeled EEG-fNIRS Synchronized Recorded Emotion Dataset"
theme: jekyll-theme-cayman
